//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanTai.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WanTaiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WanTaiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanTai.Common.Resources.WanTaiResource", typeof(WanTaiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 终止.
        /// </summary>
        public static string btnAbort {
            get {
                return ResourceManager.GetString("btnAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸取空气以代替液体.
        /// </summary>
        public static string btnAspAir {
            get {
                return ResourceManager.GetString("btnAspAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略凝块，并继续.
        /// </summary>
        public static string btnContinueIgnore {
            get {
                return ResourceManager.GetString("btnContinueIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续，但报错通道不加样.
        /// </summary>
        public static string btnContinueNothing {
            get {
                return ResourceManager.GetString("btnContinueNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略错误并继续加样.
        /// </summary>
        public static string btnContinuePipette {
            get {
                return ResourceManager.GetString("btnContinuePipette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续，但丢失吸头通道不加样.
        /// </summary>
        public static string btnContLostDiTiPipet {
            get {
                return ResourceManager.GetString("btnContLostDiTiPipet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 液体打回原位，然后放弃这个样本.
        /// </summary>
        public static string btnDispensePipetNone {
            get {
                return ResourceManager.GetString("btnDispensePipetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 液体打回到原有位置.
        /// </summary>
        public static string btnDispenseRetry {
            get {
                return ResourceManager.GetString("btnDispenseRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续，但报错吸头不加样.
        /// </summary>
        public static string btnDiTiContPipetNone {
            get {
                return ResourceManager.GetString("btnDiTiContPipetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打掉报错通道吸头并重取.
        /// </summary>
        public static string btnEjectThenMountNewDiTi {
            get {
                return ResourceManager.GetString("btnEjectThenMountNewDiTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string BtnEnter {
            get {
                return ResourceManager.GetString("BtnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录凝块信息，并继续.
        /// </summary>
        public static string btnGoWithClot {
            get {
                return ResourceManager.GetString("btnGoWithClot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string BtnHelp {
            get {
                return ResourceManager.GetString("BtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到最底部吸液.
        /// </summary>
        public static string btnMoveZMax {
            get {
                return ResourceManager.GetString("btnMoveZMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把枪头缩回到最高位.
        /// </summary>
        public static string btnMoveZTravel {
            get {
                return ResourceManager.GetString("btnMoveZTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 覆盖.
        /// </summary>
        public static string BtnOverwrite {
            get {
                return ResourceManager.GetString("BtnOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 什么都不吸取.
        /// </summary>
        public static string btnPipetNothing {
            get {
                return ResourceManager.GetString("btnPipetNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试.
        /// </summary>
        public static string BtnRetry {
            get {
                return ResourceManager.GetString("BtnRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新探测.
        /// </summary>
        public static string btnRetryDetect {
            get {
                return ResourceManager.GetString("btnRetryDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再次锁定.
        /// </summary>
        public static string BtnSwitchLock {
            get {
                return ResourceManager.GetString("BtnSwitchLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到凝块.
        /// </summary>
        public static string clotdetected {
            get {
                return ResourceManager.GetString("clotdetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超出最大容量.
        /// </summary>
        public static string DiluterOverflowError {
            get {
                return ResourceManager.GetString("DiluterOverflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸头已经装配.
        /// </summary>
        public static string DiTialreadymounted {
            get {
                return ResourceManager.GetString("DiTialreadymounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        public static string DiTifetched {
            get {
                return ResourceManager.GetString("DiTifetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸头丢失.
        /// </summary>
        public static string DiTihasbeenlost {
            get {
                return ResourceManager.GetString("DiTihasbeenlost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未取到枪头.
        /// </summary>
        public static string DiTiNotfetched {
            get {
                return ResourceManager.GetString("DiTiNotfetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸头未能很好的装配.
        /// </summary>
        public static string Ditinotproperlymounted {
            get {
                return ResourceManager.GetString("Ditinotproperlymounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吸头已经完全装配.
        /// </summary>
        public static string Ditiproperlymounted {
            get {
                return ResourceManager.GetString("Ditiproperlymounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}号门锁没有锁定.
        /// </summary>
        public static string Doorlocknotactivated {
            get {
                return ResourceManager.GetString("Doorlocknotactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条码读取错误.
        /// </summary>
        public static string ErrorReadingBarcode {
            get {
                return ResourceManager.GetString("ErrorReadingBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evoware fired an event: 
        ///StartTime: {0} 
        ///EndTime: {1} 
        ///Device: {2} 
        ///Macro: {3} 
        ///Object: {4} 
        ///Message: {5} 
        ///Status: {6} 
        ///ProcessName: {7}
        ///ProcessID: {8} 
        ///MacroID: {9}.
        /// </summary>
        public static string EVOAPI_EVENTLOG {
            get {
                return ResourceManager.GetString("EVOAPI_EVENTLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定针.
        /// </summary>
        public static string Fixedtip {
            get {
                return ResourceManager.GetString("Fixedtip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未探测到液体.
        /// </summary>
        public static string NoLiquid {
            get {
                return ResourceManager.GetString("NoLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 液体量不够.
        /// </summary>
        public static string NotEnoughLiquid {
            get {
                return ResourceManager.GetString("NotEnoughLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联机失败，请检查是否打开仪器。是否重试？.
        /// </summary>
        public static string OffLineMessage {
            get {
                return ResourceManager.GetString("OffLineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVO切换到脱机状态并终止脚本.
        /// </summary>
        public static string OffLineModeMessage {
            get {
                return ResourceManager.GetString("OffLineModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常/自动处理.
        /// </summary>
        public static string OKautomatichandling {
            get {
                return ResourceManager.GetString("OKautomatichandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夹取失败.
        /// </summary>
        public static string Racknotfetched {
            get {
                return ResourceManager.GetString("Racknotfetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在下一位再试.
        /// </summary>
        public static string RetryAtNextPosition {
            get {
                return ResourceManager.GetString("RetryAtNextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在原位重试.
        /// </summary>
        public static string RetryAtSamePosition {
            get {
                return ResourceManager.GetString("RetryAtSamePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体积[ul].
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
